version: '3.8'
services:
  maintenance-service-db-postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5433:5433"
    expose:
      - "5433"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maintenance-service-db
    command: -p 5433
    volumes:
      - maintenance-ticket-db:/var/lib/postgresql/data
  progress-service-db-postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5434:5434"
    expose:
      - "5434"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: progress-service-db
    command: -p 5434
    volumes:
      - progress-db:/var/lib/postgresql/data
  equipment-service-db-mongo:
    image: mongo:7.0.0-rc6-jammy
    restart: always
    environment:
      MONGO_INITDB_DATABASE: equipment-service
    ports:
      - '27017:27017'
    volumes:
      - equipment-service-db:/data/db
  authentication-service-db-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication-server-db
    volumes:
      - auth-server-db:/var/lib/postgresql/data
    ports:
      - "5435:5434"
    expose:
      - "5434"
    command: -p 5434
  zookeeper: #orchestrate kafka cluster
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka: #the broker
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
    expose:
      - "8761"

  authentication-service:
    build:
      context:  ./authentication-server-jwt
    container_name: authentication-service
    depends_on:
      - authentication-service-db-postgres
    expose:
      - "9012"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8079"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - zipkin
      - authentication-service

  equipment-service:
    container_name: equipment-service
    build:
      context: ./equipment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - zipkin
      - equipment-service-db-mongo
      - api-gateway
    expose:
      - "9090"

  maintenance-ticket-service:
    container_name: maintenance-ticket-service
    build:
      context: ./maintenance-ticket-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - zipkin
      - maintenance-service-db-postgres
      - kafka
      - zookeeper
      - api-gateway
    expose:
      - "8081"

  progress-service:
    container_name: progress-service
    build:
      context: ./progress-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - zipkin
      - api-gateway
      - progress-service-db-postgres
    expose:
      - "8082"

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - zipkin
      - api-gateway
      - kafka
      - zookeeper
    expose:
      - "12312"



volumes:
  equipment-service-db:
  maintenance-ticket-db:
  progress-db:
  auth-server-db: