version: '3.8'
services:
  maintenance-service-db-postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5433:5433"
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maintenance-service-db
    command: -p 5433
    volumes:
      - maintenance-ticket-db:/var/lib/postgresql/data
  progress-service-db-postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5434:5434"
    expose:
      - "5434"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: progress-service-db
    command: -p 5434
    volumes:
      - progress-db:/var/lib/postgresql/data
  equipment-service-db-mongo:
    image: mongo:7.0.0-rc6-jammy
    restart: always
    environment:
      MONGO_INITDB_DATABASE: equipment-service
    ports:
      - '27017:27017'
    volumes:
      - equipment-service-db:/data/db

  authentication-service-db-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication-server-db
    volumes:
      - auth-server-db:/var/lib/postgresql/data
    ports:
      - "5435:5434"
    expose:
      - "5434"
    command: -p 5434

  zookeeper: #orchestrate kafka cluster
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka: #the broker
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
volumes:
  equipment-service-db:
  maintenance-ticket-db:
  progress-db:
  auth-server-db: