global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'equipment_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['equipment-service:8090']
        labels:
          application: 'Equipment Service Application'
  - job_name: 'maintenance_ticket_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['maintenance-ticket-service:8081']
        labels:
          application: 'Maintenance Ticket Service Application'
  - job_name: 'progress_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['progress-service:8082']
        labels:
          application: 'progress Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:12312']
        labels:
          application: 'Notification Service Application'